### ISSUE TITLE
networkx version

### ISSUE THREAD

**Issue by mmathioudakis** [harrymvr/absorbing-centrality#9]
Currently, installation requires nexworkx version 1.9.1,  which causes newer versions to uninstall.
Can we relax the requirement to allow for newer versions of networkx?

**Comment by harrymvr** [comment]
That should be pretty easy. I think there was a change in some functions of networkx that now returns a set instead of a list. I'll look into it.

**Comment by harrymvr** [comment]
#10 fixes this issue.
